### ISSUE TITLE
People are starting to ask if they're allowed to use this in packs, maybe we should include a license?

### ISSUE THREAD

**Issue by GeorgeWL** [eddoww/modded-schematics#10]
I would recommend CCA

Basically means:

> As long as you link back to the Repo in a publicly visible place (such as the project overview if you're using curseforge) , then you may use this project for any purpose without having to ask for permission.

_Sent from my Pixel 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eddoww** [comment]
Isn't that the same as MIT?

**Comment by eddoww** [comment]
I do totally agree however to include a license, and people are obviously free to use it in modpacks.

**Comment by GeorgeWL** [comment]
I think so, only difference is MIT allows modifications without express permission.


Which actually we do want.  Maybe we should just put a little note about it in the Readme? 

I'll make a PR for it now.

**Comment by GeorgeWL** [comment]
https://github.com/eddoww/modded-schematics/pull/11/commits/7f59cd4369387c9e4400623458cc5e92cf91a21e

**Comment by eddoww** [comment]
I've added the license.md file to work nicely with github. Not sure if we need to include it in readme.md?

**Comment by GeorgeWL** [comment]
ah, no harm in reminding people I suppose though.
